/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ApplicationsRouteImport } from './routes/applications'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProfileSeekerRouteImport } from './routes/profile/seeker'
import { Route as ProfileEmployerRouteImport } from './routes/profile/employer'
import { Route as JobsCreateRouteImport } from './routes/jobs/create'
import { Route as DashboardSeekerRouteImport } from './routes/dashboard/seeker'
import { Route as DashboardJobsRouteImport } from './routes/dashboard/jobs'
import { Route as DashboardEmployerRouteImport } from './routes/dashboard/employer'
import { Route as ApplicantIdRouteImport } from './routes/applicant/$id'
import { Route as JobsIdIndexRouteImport } from './routes/jobs/$id/index'
import { Route as JobsIdApplicantsRouteImport } from './routes/jobs/$id/applicants'

const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplicationsRoute = ApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileSeekerRoute = ProfileSeekerRouteImport.update({
  id: '/profile/seeker',
  path: '/profile/seeker',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileEmployerRoute = ProfileEmployerRouteImport.update({
  id: '/profile/employer',
  path: '/profile/employer',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsCreateRoute = JobsCreateRouteImport.update({
  id: '/jobs/create',
  path: '/jobs/create',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSeekerRoute = DashboardSeekerRouteImport.update({
  id: '/dashboard/seeker',
  path: '/dashboard/seeker',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardJobsRoute = DashboardJobsRouteImport.update({
  id: '/dashboard/jobs',
  path: '/dashboard/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardEmployerRoute = DashboardEmployerRouteImport.update({
  id: '/dashboard/employer',
  path: '/dashboard/employer',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplicantIdRoute = ApplicantIdRouteImport.update({
  id: '/applicant/$id',
  path: '/applicant/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsIdIndexRoute = JobsIdIndexRouteImport.update({
  id: '/jobs/$id/',
  path: '/jobs/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsIdApplicantsRoute = JobsIdApplicantsRouteImport.update({
  id: '/jobs/$id/applicants',
  path: '/jobs/$id/applicants',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/applications': typeof ApplicationsRoute
  '/settings': typeof SettingsRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/applicant/$id': typeof ApplicantIdRoute
  '/dashboard/employer': typeof DashboardEmployerRoute
  '/dashboard/jobs': typeof DashboardJobsRoute
  '/dashboard/seeker': typeof DashboardSeekerRoute
  '/jobs/create': typeof JobsCreateRoute
  '/profile/employer': typeof ProfileEmployerRoute
  '/profile/seeker': typeof ProfileSeekerRoute
  '/jobs/$id/applicants': typeof JobsIdApplicantsRoute
  '/jobs/$id/': typeof JobsIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/applications': typeof ApplicationsRoute
  '/settings': typeof SettingsRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/applicant/$id': typeof ApplicantIdRoute
  '/dashboard/employer': typeof DashboardEmployerRoute
  '/dashboard/jobs': typeof DashboardJobsRoute
  '/dashboard/seeker': typeof DashboardSeekerRoute
  '/jobs/create': typeof JobsCreateRoute
  '/profile/employer': typeof ProfileEmployerRoute
  '/profile/seeker': typeof ProfileSeekerRoute
  '/jobs/$id/applicants': typeof JobsIdApplicantsRoute
  '/jobs/$id': typeof JobsIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/applications': typeof ApplicationsRoute
  '/settings': typeof SettingsRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/applicant/$id': typeof ApplicantIdRoute
  '/dashboard/employer': typeof DashboardEmployerRoute
  '/dashboard/jobs': typeof DashboardJobsRoute
  '/dashboard/seeker': typeof DashboardSeekerRoute
  '/jobs/create': typeof JobsCreateRoute
  '/profile/employer': typeof ProfileEmployerRoute
  '/profile/seeker': typeof ProfileSeekerRoute
  '/jobs/$id/applicants': typeof JobsIdApplicantsRoute
  '/jobs/$id/': typeof JobsIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/applications'
    | '/settings'
    | '/sign-in'
    | '/sign-up'
    | '/applicant/$id'
    | '/dashboard/employer'
    | '/dashboard/jobs'
    | '/dashboard/seeker'
    | '/jobs/create'
    | '/profile/employer'
    | '/profile/seeker'
    | '/jobs/$id/applicants'
    | '/jobs/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/applications'
    | '/settings'
    | '/sign-in'
    | '/sign-up'
    | '/applicant/$id'
    | '/dashboard/employer'
    | '/dashboard/jobs'
    | '/dashboard/seeker'
    | '/jobs/create'
    | '/profile/employer'
    | '/profile/seeker'
    | '/jobs/$id/applicants'
    | '/jobs/$id'
  id:
    | '__root__'
    | '/'
    | '/applications'
    | '/settings'
    | '/sign-in'
    | '/sign-up'
    | '/applicant/$id'
    | '/dashboard/employer'
    | '/dashboard/jobs'
    | '/dashboard/seeker'
    | '/jobs/create'
    | '/profile/employer'
    | '/profile/seeker'
    | '/jobs/$id/applicants'
    | '/jobs/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApplicationsRoute: typeof ApplicationsRoute
  SettingsRoute: typeof SettingsRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  ApplicantIdRoute: typeof ApplicantIdRoute
  DashboardEmployerRoute: typeof DashboardEmployerRoute
  DashboardJobsRoute: typeof DashboardJobsRoute
  DashboardSeekerRoute: typeof DashboardSeekerRoute
  JobsCreateRoute: typeof JobsCreateRoute
  ProfileEmployerRoute: typeof ProfileEmployerRoute
  ProfileSeekerRoute: typeof ProfileSeekerRoute
  JobsIdApplicantsRoute: typeof JobsIdApplicantsRoute
  JobsIdIndexRoute: typeof JobsIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/applications': {
      id: '/applications'
      path: '/applications'
      fullPath: '/applications'
      preLoaderRoute: typeof ApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/seeker': {
      id: '/profile/seeker'
      path: '/profile/seeker'
      fullPath: '/profile/seeker'
      preLoaderRoute: typeof ProfileSeekerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/employer': {
      id: '/profile/employer'
      path: '/profile/employer'
      fullPath: '/profile/employer'
      preLoaderRoute: typeof ProfileEmployerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/create': {
      id: '/jobs/create'
      path: '/jobs/create'
      fullPath: '/jobs/create'
      preLoaderRoute: typeof JobsCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/seeker': {
      id: '/dashboard/seeker'
      path: '/dashboard/seeker'
      fullPath: '/dashboard/seeker'
      preLoaderRoute: typeof DashboardSeekerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/jobs': {
      id: '/dashboard/jobs'
      path: '/dashboard/jobs'
      fullPath: '/dashboard/jobs'
      preLoaderRoute: typeof DashboardJobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/employer': {
      id: '/dashboard/employer'
      path: '/dashboard/employer'
      fullPath: '/dashboard/employer'
      preLoaderRoute: typeof DashboardEmployerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/applicant/$id': {
      id: '/applicant/$id'
      path: '/applicant/$id'
      fullPath: '/applicant/$id'
      preLoaderRoute: typeof ApplicantIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/$id/': {
      id: '/jobs/$id/'
      path: '/jobs/$id'
      fullPath: '/jobs/$id/'
      preLoaderRoute: typeof JobsIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/$id/applicants': {
      id: '/jobs/$id/applicants'
      path: '/jobs/$id/applicants'
      fullPath: '/jobs/$id/applicants'
      preLoaderRoute: typeof JobsIdApplicantsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApplicationsRoute: ApplicationsRoute,
  SettingsRoute: SettingsRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  ApplicantIdRoute: ApplicantIdRoute,
  DashboardEmployerRoute: DashboardEmployerRoute,
  DashboardJobsRoute: DashboardJobsRoute,
  DashboardSeekerRoute: DashboardSeekerRoute,
  JobsCreateRoute: JobsCreateRoute,
  ProfileEmployerRoute: ProfileEmployerRoute,
  ProfileSeekerRoute: ProfileSeekerRoute,
  JobsIdApplicantsRoute: JobsIdApplicantsRoute,
  JobsIdIndexRoute: JobsIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
